# Generated by Django 2.2.4 on 2019-08-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190828_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
